
export const skills = {
  default: [
    { skill: "NextJS", img: "../public/assets/logo/nextjs-icon.svg" },
    { skill: "React", img: "../public/assets/logo/react.svg" },
    { skill: "PostgreSQL", img: "../public/assets/logo/postgresql.svg" },
    { skill: "MongoDB", img: "../public/assets/logo/mongodb-icon.svg" },
    { skill: "NodeJS", img: "../public/assets/logo/nodejs.svg" },
    { skill: "Typescript", img: "../public/assets/logo/typescript-icon.svg" },
    { skill: "Javascript", img: "../public/assets/logo/javascript.svg" },
    { skill: "Turborepo", img: "../public/assets/logo/turborepo-icon.svg" },
    { skill: "Github", img: "../public/assets/logo/github-icon.svg" },
    { skill: "Docker", img: "../public/assets/logo/docker-icon.svg" },
    { skill: "AWS", img: "../public/assets/logo/aws.svg" },
    { skill: "Java", img: "../public/assets/logo/java.svg" },
    { skill: "Python", img: "../public/assets/logo/python.svg" },
  ],
  frontend: [
    { skill: "React", img: "../public/assets/logo/react.svg" },
    { skill: "NextJS", img: "../public/assets/logo/nextjs-icon.svg" },
    { skill: "Flutter", img: "../public/assets/logo/flutter.svg" },
    { skill: "Tailwind CSS", img: "../public/assets/logo/tailwindcss-icon.svg" },
    { skill: "ShadCN", img: "../public/assets/logo/shadcn.svg" },
    { skill: "Aceternity", img: "../public/assets/logo/aceternity.svg" },
  ],
  backend: [
    { skill: "Node.js", img: "../public/assets/logo/nodejs.svg" },
    { skill: "Express.js", img: "../public/assets/logo/express.svg" },
    { skill: "Cloudflare Workers", img: "../public/assets/logo/cloudflare-workers.svg" },
    { skill: "Firebase", img: "../public/assets/logo/firebase.svg" },
  ],
  database: [
    { skill: "MongoDB", img: "../public/assets/logo/mongodb-icon.svg" },
    { skill: "PostgreSQL", img: "../public/assets/logo/postgresql.svg" },
    { skill: "MySQL", img: "../public/assets/logo/mysql-icon.svg" },
    { skill: "Firebase", img: "../public/assets/logo/firebase.svg" },
  ],
  tools: [
    { skill: "Docker", img: "../public/assets/logo/docker-icon.svg" },
    { skill: "Git", img: "../public/assets/logo/git-icon.svg" },
    { skill: "Github", img: "../public/assets/logo/github-icon.svg" },
    { skill: "Vscode", img: "../public/assets/logo/visual-studio-code.svg" },
    { skill: "Neovim", img: "../public/assets/logo/neovim.svg" },
    { skill: "Bash", img: "../public/assets/logo/bash.svg" },
    { skill: "Prisma", img: "../public/assets/logo/prisma.svg" },
  ],
  devops: [
    { skill: "AWS", img: "../public/assets/logo/aws.svg" },
    { skill: "Cloudflare", img: "../public/assets/logo/cloudflare-icon.svg" },
    { skill: "CI/CD", img: "../public/assets/logo/ci-cd.svg" },
  ],
};
